sonar.projectKey=OmerSiddiqui778_8.2CDevSecOps
sonar.organization=omersiddiqui778 
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
# Note: Use a lowercase 'l' for lcov, not a capital 'I'
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8